### ISSUE TITLE
multiple instances in one file

### ISSUE THREAD

**Issue by gsgs2** [potassco/clasp#100]
... for testing and comparing solvers

you can just merge the .sat files , a new instance starts with p cnf x z

when clasp has finished one instance it should just continue with the next

that's easier than .sh scripts or selfwritten programs to split the file and call clasp on each instance separately

**Comment by BenKaufmann** [comment]
I'm not sure I understand the motivation of this. 

- Is there any SAT (or other) solver supporting such kind of "merged multi-instance" scenario? I briefly looked into kissat/cadical, glucose/MiniSAT, as well as cryptominisat and none of them supports this.  kissat/cadical will bail out with a parse error, while the other solvers will (silently) solve the combined instance thereby producing a probably unwanted result.
- Where are the merged files coming from? Typically, benchmark sets (e.g. from the competitions) have each instance in a separate file. 
- Why not just split the merged file into separate files, e.g. via something like `csplit -sz <combined-file> /"p cnf"/ '{*}'`, and then use a simple (shell) loop? This seems way more flexible and efficient (e.g. running multiple instances in parallel, less memory fragmentation, ...).

Anyhow, while looking into this I realized that the dimacs parser in `clasp` is actually buggy when it comes to handling unexpected characters. In this particular scenario, it enters an infinite loop instead of either failing (like e.g. kissat) or ignoring subsequent `p` lines (like many other solvers).

**Comment by gsgs2** [comment]
Chalaturnyk's Hamiltonian Cycle solver does support it.
That was the first solver I installed in 2023
and I learned to like that feature and I'm surprised why
other programs don't support it.
These days you are usually testing multiple instances and
comparing the statistic since one instance - is just random.

My benchmarks of increasing sizes are created by computer ,
in a seeded randmized process.

Why would they split the SAT-competition files
into multiple files ? I think it's just historical,
"DIMACS-format"

shell-loops are obviously another level of encomplification.
All the files in the directory are hard to overview
and each time you change a parameter you need a new shell-loop


actually I'm using ./claspa file  which calls system("clasp kk --quiet 
 >> ll")
on each instance kk of file
But now I want to try other parameters


Am 13.05.2024 09:55 schrieb Benjamin Kaufmann:

**Comment by rkaminsk** [comment]
> shell-loops are obviously another level of encomplification. All the files in the directory are hard to overview and each time you change a parameter you need a new shell-loop

There are tools available that should support your use case. You can try to adjust the snippet using [GNU parallel](https://www.gnu.org/software/parallel/parallel_examples.html) to your use case.

```
$ echo -en 'p cnf 1 1\n1 1\np cnf\n2 2\n1 1\n1 2\n' | parallel --pipe -N1 --recstart "p cnf" cat -n
     1	p cnf 1 1
     2	1 1
     1	p cnf
     2	2 2
     3	1 1
     4	1 2
```

On another note, I am not convinced that a single file with all the instances is a good way to store the instances. It might be okay for running all instances sequentially but fails any other use case. Also consider the following one-liner to run a command for each file in a directory:

```
$ find instances/ -type f -exec echo {} \;
```
