### ISSUE TITLE
-n0 does not work with domain-atom heuristic programming

### ISSUE THREAD

**Issue by votacom** [potassco/clasp#15]
It seems that when using the flags `--enum=domRec --heuristic=Domain` together with `#heuristic` directives, the `-n`/`--models` flag gets ignored.

Steps to reproduce:

```
#> clingo --enum=domRec --heuristic=Domain -n0
clingo version 5.2.2
Reading from stdin

{guess(1..3)}.
-b|b.
#heuristic guess(1..3). [1,false] 

Solving...
Answer: 1
-b
SATISFIABLE

Models       : 1
Calls        : 1
Time         : 2.411s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.001s
```

I expected a second answer set, consisting of `b`.

**Comment by votacom** [comment]
I am sorry, I seem to have misunderstood the semantics of the Domain heuristic. Of course the `-n0` flag also works here, clasp just stops searching for further answer sets with the *same* Domain atoms.

Is there a way, though, to accomplish to output *all* answer sets which are subset/superset-minimal w.r.t. a certain set of atoms?

**Comment by rkaminsk** [comment]
Hi, I think the issue here is how the domRec enumeration mode works. It cuts of all further answer sets that are supersets (inclusive) of the heuristically modified atoms. You seem to want an enumeration mode that cuts the current model and strict supersets of the heuristically modified atoms, which is not offered out-of-the-box by clingo. What you can do is use the python API to implement your own enumeration scheme. You can add additional constraints whenever there is a model. This should allow you to achieve what you want to do.
