### ISSUE TITLE
gringo's output causes clasp to generate too many IDs

### ISSUE THREAD

**Issue by davegomboc** [potassco/clasp#25]
I have a 28 GB output file from gringo that clasp cannot handle.  After several minutes of processing, it bails out with:

*** ERROR: (clasp): Clasp::Asp::PrgNode::PrgNode(Clasp::uint32, bool)@404: Value too large for defined data type: Id out of range

I believe this assert is the POTASSCO_CHECK in PrgNode's constructor in logic_program_types.cpp and is because 32-bit integer ids are used.

My guess is that the natural fix would be to transition to using 64-bit integer ids.

**Comment by davegomboc** [comment]
Or, perhaps I misinterpreted the error last night, and it's simply attempting to store a uint32 into a bool?

I can try building my own clasp (instead of using a distro's version) and instrumenting with ASAN and the like.  What else would you suggest I try out to help narrow things down?  I'm not confident I can reduce the 28 GB input to something small enough to be reasonable.

**Comment by rkaminsk** [comment]
clasp only supports `2^28` (or so) different atoms. If there are more in the grounding than it will fail. There is no easy way to switch to 64bit integers because clasp's data structures are highly tuned and assume 32bit integers for atom ids.

**Comment by BenKaufmann** [comment]
To add to Roland's comment: With some extra work, one could quadruple the number of supported atoms to `2^30` , which equals the number of supported variables in the backend-solver. Everything above that would basically require a complete redesign of clasp in order to still achieve any kind of good performance. But to be honest, I doubt that doing classical CDCL would make any sense on a problem with a billion plus variables.
